### ISSUE TITLE
Upgrade to Debian 8

### ISSUE THREAD

**Issue by kniklas** [kniklas/ropsi-debian-dev-env#26]
### Dependencies and Notes
- [x] Consider to perform this upgrade on copy of Virtual Machine
- [x] Verify if Python is upgraded and if Vim python3-dyn works fine
- [x] Verify if Vim should be re-installed from package or recompiled again
- [x] Verify if Vim blinking still appears - #27 
- [x] Verify if Midori issues are solved - #22 
- [x] Consider dependency with xclip - #23 
- [x] Consider dependency with Cantera upgrade - #25
### Links

http://www.linuxveda.com/2015/04/28/upgrade-from-debian-7-to-debian-8/
https://www.debian.org/releases/stable/amd64/release-notes/ch-upgrading

**Comment by kniklas** [comment]
After upgrade to Debian 8 Midori and xclip issues have not been resolved, they should be followed-up in separate issues.

**Comment by kniklas** [comment]
After upgrade VIM blinking issues have not been observed, but it might be caused by fact VIM was not intensively used yet.

**Comment by kniklas** [comment]
Cantera upgrade to be followed-up on separate ticket. This issue can be closed now (Debian upgrade done).
